import type {
  ArpStep,
  DrumPattern,
  Drum2Pattern,
  Drum2Voices,
  EditableAudioNodeType,
  SoundNodeData,
} from './types';

const defaultDrumPattern = (): DrumPattern => ({
  kick: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
  snare: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
  hihat: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true],
});

const defaultDrum2Pattern = (): Drum2Pattern => ({
  kick: Array.from({ length: 32 }, (_, index) => [0, 4, 8, 12].includes(index)),
  snare: Array.from({ length: 32 }, (_, index) => [4, 12].includes(index)),
  hihat: Array.from({ length: 32 }, (_, index) => [0, 2, 4, 6, 8, 10, 12, 14].includes(index)),
  tom: Array.from({ length: 32 }, () => false),
  fx: Array.from({ length: 32 }, () => false),
  cymbal: Array.from({ length: 32 }, (_, index) => [15].includes(index)),
});

const defaultDrum2Voices = (): Drum2Voices => ({
  kick: { tone: 52, decay: 0.26, gain: 0.95, shape: 0.6 },
  snare: { tone: 190, decay: 0.16, gain: 0.68, shape: 0.55 },
  hihat: { tone: 9800, decay: 0.05, gain: 0.38, shape: 0.5 },
  tom: { tone: 140, decay: 0.24, gain: 0.48, shape: 0.4 },
  fx: { tone: 2100, decay: 0.18, gain: 0.26, shape: 0.42 },
  cymbal: { tone: 7400, decay: 0.62, gain: 0.34, shape: 0.72 },
});

const defaultArpSteps = (): ArpStep[] => [
  { note: 'C', octave: 4, enabled: true },
  { note: 'E', octave: 4, enabled: true },
  { note: 'G', octave: 4, enabled: true },
  { note: 'B', octave: 4, enabled: true },
  { note: 'C', octave: 5, enabled: true },
  { note: 'B', octave: 4, enabled: true },
  { note: 'G', octave: 4, enabled: true },
  { note: 'E', octave: 4, enabled: true },
];

const defaultArp2Steps = (): ArpStep[] => [
  { note: 'C', octave: 3, enabled: true },
  { note: 'G', octave: 3, enabled: false },
  { note: 'A#', octave: 3, enabled: true },
  { note: 'D', octave: 4, enabled: true },
  { note: 'F', octave: 4, enabled: true },
  { note: 'A', octave: 4, enabled: false },
  { note: 'C', octave: 5, enabled: true },
  { note: 'D#', octave: 5, enabled: true },
  { note: 'C', octave: 4, enabled: true },
  { note: 'G', octave: 3, enabled: false },
  { note: 'F', octave: 3, enabled: true },
  { note: 'A#', octave: 3, enabled: true },
  { note: 'D', octave: 4, enabled: false },
  { note: 'F', octave: 4, enabled: true },
  { note: 'G', octave: 4, enabled: true },
  { note: 'C', octave: 5, enabled: true },
];

const defaultEqBands = () => [0, 0, 0, 0, 0, 0, 0, 0];

export const defaultNodeData: Record<EditableAudioNodeType, SoundNodeData> = {
  oscillator: {
    label: 'Oscillator',
    frequency: 440,
    type: 'sine',
  },
  dualOsc: {
    label: 'Dual Osc',
    frequency: 220,
    gain: 0.35,
    type: 'sawtooth',
    modType: 'square',
    detune: 12,
    blend: 0.5,
  },
  dronePad: {
    label: 'Drone Pad',
    note: 'C',
    octave: 3,
    chordType: 'minor',
    spread: 14,
    gain: 0.25,
    type: 'sawtooth',
  },
  bassline: {
    label: 'Bassline',
    note: 'C',
    octave: 2,
    tone: 900,
    gain: 0.45,
    syncDivision: '1/16',
    steps: Array.from({ length: 16 }, (_, index) => index % 4 === 0),
  },
  leadVoice: {
    label: 'Lead Voice',
    frequency: 330,
    tone: 2200,
    Q: 0.8,
    gain: 0.3,
    glide: 0.04,
    type: 'sawtooth',
  },
  sampler: {
    label: 'Sampler',
    gain: 0.85,
    playbackRate: 1,
    loop: false,
    sampleDataUrl: '',
    sampleName: '',
    triggerNonce: 0,
    stopNonce: 0,
  },
  vocoder: {
    label: 'Vocoder',
    vocoderSource: 'microphone',
    micEnabled: false,
    gain: 0.95,
    mix: 1,
    tone: 5200,
    Q: 14,
    attack: 0.004,
    release: 0.06,
    bands: 16,
  },
  daftVoice: {
    label: 'Daft Voice',
    micEnabled: false,
    gain: 0.95,
    mix: 1,
    frequency: 88,
    tone: 3200,
    Q: 10,
    drive: 3,
  },
  gain: {
    label: 'Gain',
    gain: 0.5,
  },
  filter: {
    label: 'Filter',
    frequency: 1000,
    type: 'lowpass',
    Q: 1,
  },
  delay: {
    label: 'Delay',
    delayTime: 0.3,
    sync: false,
    syncDivision: '1/8',
  },
  spectralDelay: {
    label: 'Spectral Delay',
    delayTime: 0.18,
    sync: false,
    syncDivision: '1/8',
    spread: 0.45,
    texture: 0.55,
    feedback: 0.42,
    mix: 0.72,
    tone: 1600,
  },
  noise: {
    label: 'Noise',
  },
  distortion: {
    label: 'Distortion',
    distortion: 400,
  },
  reverb: {
    label: 'Reverb',
    decay: 3,
    roomSize: 0.55,
    delayTime: 0.02,
    tone: 4800,
    mix: 0.55,
  },
  compressor: {
    label: 'Compressor',
    threshold: -24,
    knee: 18,
    ratio: 6,
    attack: 0.01,
    release: 0.25,
    makeup: 1,
  },
  channelStrip: {
    label: 'Channel Strip',
    gateThreshold: -72,
    threshold: -24,
    knee: 18,
    ratio: 4,
    attack: 0.01,
    release: 0.2,
    makeup: 1,
    highpassFrequency: 30,
    lowpassFrequency: 18000,
    band1Gain: 0,
    band1Q: 0.7,
    band2Gain: 0,
    band2Q: 0.9,
    band3Gain: 0,
    band3Q: 1.1,
    band4Gain: 0,
    band4Q: 0.7,
  },
  chorus: {
    label: 'Chorus',
    rate: 0.8,
    depth: 0.012,
    delay: 0.02,
    mix: 0.45,
    sync: false,
    syncDivision: '1/4',
  },
  bitcrusher: {
    label: 'Bitcrusher',
    bits: 6,
    normFreq: 0.2,
    mix: 0.7,
  },
  flanger: {
    label: 'Flanger',
    rate: 0.25,
    depth: 0.003,
    feedback: 0.55,
    mix: 0.5,
    sync: false,
    syncDivision: '1/4',
  },
  limiter: {
    label: 'Limiter',
    threshold: -6,
    release: 0.08,
    makeup: 1,
  },
  looper: {
    label: 'Looper',
    loopLength: 0.5,
    feedback: 0.2,
    mix: 0.8,
    sync: true,
    syncDivision: '1/4',
    freeze: false,
  },
  tremolo: {
    label: 'Tremolo',
    rate: 4,
    depth: 0.75,
    mix: 1,
    sync: false,
    syncDivision: '1/8',
  },
  ringMod: {
    label: 'Ring Mod',
    modFrequency: 60,
    depth: 1,
    mix: 0.8,
    sync: false,
    syncDivision: '1/8',
  },
  vibrato: {
    label: 'Vibrato',
    rate: 5,
    depth: 0.004,
    mix: 1,
    sync: false,
    syncDivision: '1/8',
  },
  combFilter: {
    label: 'Comb Filter',
    delay: 0.015,
    feedback: 0.65,
    mix: 0.7,
  },
  autoPan: {
    label: 'AutoPan',
    rate: 0.5,
    depth: 1,
    mix: 1,
    sync: false,
    syncDivision: '1/4',
  },
  autoFilter: {
    label: 'AutoFilter',
    type: 'lowpass',
    rate: 0.8,
    depth: 2200,
    tone: 800,
    Q: 1.2,
    mix: 0.85,
    sync: false,
    syncDivision: '1/8',
  },
  clockDivider: {
    label: 'Clock Divider',
    syncDivision: '1/4',
  },
  randomCv: {
    label: 'Random CV',
    minValue: -300,
    maxValue: 300,
    syncDivision: '1/8',
  },
  sampleHold: {
    label: 'Sample Hold',
    rate: 8,
    mix: 1,
    sync: false,
    syncDivision: '1/16',
  },
  gateSeq: {
    label: 'Gate Seq',
    syncDivision: '1/16',
    steps: Array.from({ length: 16 }, (_, index) => index % 2 === 0),
  },
  cvOffset: {
    label: 'CV Offset',
    offset: 0,
    gain: 1,
  },
  envelopeFollower: {
    label: 'Envelope Follower',
    attack: 0.03,
    release: 0.18,
    gain: 200,
  },
  quantizer: {
    label: 'Quantizer',
    divider: 12,
    mix: 1,
  },
  comparator: {
    label: 'Comparator',
    threshold: 0,
  },
  lag: {
    label: 'Lag',
    attack: 0.02,
    release: 0.08,
    mix: 1,
  },
  chordSeq: {
    label: 'Chord Seq',
    note: 'C',
    octave: 3,
    chordType: 'major',
    spread: 10,
    gain: 0.22,
    syncDivision: '1/4',
    steps: Array.from({ length: 16 }, (_, index) => index % 4 === 0),
  },
  resonator: {
    label: 'Resonator',
    tone: 440,
    Q: 12,
    spread: 7,
    mix: 0.7,
  },
  wah: {
    label: 'Wah',
    rate: 1.5,
    depth: 900,
    tone: 700,
    Q: 8,
    mix: 0.75,
    sync: false,
    syncDivision: '1/8',
  },
  stereoWidener: {
    label: 'Stereo Widener',
    delay: 0.012,
    spread: 1,
    mix: 0.65,
  },
  foldback: {
    label: 'Foldback',
    drive: 2.2,
    threshold: 0.55,
    mix: 0.75,
  },
  tiltEq: {
    label: 'Tilt EQ',
    tone: 900,
    tilt: 0,
    mix: 1,
  },
  saturator: {
    label: 'Saturator',
    drive: 2.4,
    makeup: 1,
    mix: 0.8,
  },
  cabSim: {
    label: 'Cab Sim',
    tone: 2600,
    Q: 0.8,
    mix: 1,
  },
  transientShaper: {
    label: 'Transient',
    attack: 0.7,
    sustain: 0,
    mix: 1,
  },
  freezeFx: {
    label: 'Freeze',
    loopLength: 0.35,
    mix: 0.9,
    freeze: false,
    sync: false,
    syncDivision: '1/4',
  },
  granular: {
    label: 'Granular',
    grainSize: 0.12,
    spray: 0.35,
    mix: 0.8,
    sync: false,
    syncDivision: '1/8',
  },
  stutter: {
    label: 'Stutter',
    loopLength: 0.12,
    mix: 0.8,
    sync: false,
    syncDivision: '1/8',
  },
  humanizer: {
    label: 'Humanizer',
    rate: 2,
    depth: 0.35,
    mix: 0.7,
  },
  triggerDelay: {
    label: 'Trigger Delay',
    delayTime: 0.08,
    mix: 1,
    sync: false,
    syncDivision: '1/16',
  },
  monoSynth: {
    label: 'Mono Synth',
    frequency: 220,
    gain: 0.35,
    tone: 1800,
    Q: 0.8,
    type: 'sawtooth',
  },
  kickSynth: {
    label: 'Kick Synth',
    gain: 0.9,
    tone: 58,
    decay: 0.24,
    steps: [true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false],
  },
  snareSynth: {
    label: 'Snare Synth',
    gain: 0.65,
    tone: 180,
    decay: 0.16,
    steps: [false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false],
  },
  hiHatSynth: {
    label: 'HiHat Synth',
    gain: 0.4,
    tone: 9500,
    decay: 0.06,
    steps: Array.from({ length: 16 }, () => true),
  },
  chordGenerator: {
    label: 'Chord Generator',
    note: 'C',
    octave: 4,
    chordType: 'major',
    spread: 10,
    gain: 0.22,
    type: 'triangle',
  },
  scope: {
    label: 'Scope',
  },
  vuMeter: {
    label: 'VU Meter',
  },
  phaseCorrelator: {
    label: 'Phase Correlator',
  },
  lissajous: {
    label: 'Lissajous',
  },
  tuner: {
    label: 'Tuner',
  },
  mixer: {
    label: 'Mixer',
    ch1: 0.5,
    ch2: 0.5,
    ch3: 0.5,
    ch4: 0.5,
    ch5: 0.5,
    ch6: 0.5,
    ch7: 0.5,
    ch8: 0.5,
    ch1_low: 0,
    ch1_mid: 0,
    ch1_high: 0,
    ch1_pan: 0,
    ch1_mute: false,
    ch1_solo: false,
    ch1_gate: 0,
    ch1_comp: 0.18,
    ch1_room: 0,
    ch1_delay: 0,
    ch2_low: 0,
    ch2_mid: 0,
    ch2_high: 0,
    ch2_pan: 0,
    ch2_mute: false,
    ch2_solo: false,
    ch2_gate: 0,
    ch2_comp: 0.18,
    ch2_room: 0,
    ch2_delay: 0,
    ch3_low: 0,
    ch3_mid: 0,
    ch3_high: 0,
    ch3_pan: 0,
    ch3_mute: false,
    ch3_solo: false,
    ch3_gate: 0,
    ch3_comp: 0.18,
    ch3_room: 0,
    ch3_delay: 0,
    ch4_low: 0,
    ch4_mid: 0,
    ch4_high: 0,
    ch4_pan: 0,
    ch4_mute: false,
    ch4_solo: false,
    ch4_gate: 0,
    ch4_comp: 0.18,
    ch4_room: 0,
    ch4_delay: 0,
    ch5_low: 0,
    ch5_mid: 0,
    ch5_high: 0,
    ch5_pan: 0,
    ch5_mute: false,
    ch5_solo: false,
    ch5_gate: 0,
    ch5_comp: 0.18,
    ch5_room: 0,
    ch5_delay: 0,
    ch6_low: 0,
    ch6_mid: 0,
    ch6_high: 0,
    ch6_pan: 0,
    ch6_mute: false,
    ch6_solo: false,
    ch6_gate: 0,
    ch6_comp: 0.18,
    ch6_room: 0,
    ch6_delay: 0,
    ch7_low: 0,
    ch7_mid: 0,
    ch7_high: 0,
    ch7_pan: 0,
    ch7_mute: false,
    ch7_solo: false,
    ch7_gate: 0,
    ch7_comp: 0.18,
    ch7_room: 0,
    ch7_delay: 0,
    ch8_low: 0,
    ch8_mid: 0,
    ch8_high: 0,
    ch8_pan: 0,
    ch8_mute: false,
    ch8_solo: false,
    ch8_gate: 0,
    ch8_comp: 0.18,
    ch8_room: 0,
    ch8_delay: 0,
    roomSize: 0.58,
    decay: 2.8,
    sync: true,
    syncDivision: '1/8',
    delayTime: 0.28,
    feedback: 0.36,
    tone: 4800,
    roomReturn: 0.24,
    delayReturn: 0.22,
  },
  spectrogram: {
    label: 'Spectrogram',
  },
  panner: {
    label: 'Panner',
    pan: 0,
  },
  lfo: {
    label: 'LFO',
    frequency: 1,
    gain: 100,
    type: 'sine',
    sync: false,
    syncDivision: '1/4',
  },
  drumMachine: {
    label: 'Drum Machine',
    bpm: 120,
    drumPattern: defaultDrumPattern(),
  },
  drum2: {
    label: 'DRUM2',
    bpm: 120,
    drum2Length: 16,
    drum2Pattern: defaultDrum2Pattern(),
    drum2Voices: defaultDrum2Voices(),
  },
  arpeggiator: {
    label: 'Arpeggiator',
    syncDivision: '1/8',
    arpMode: 'up',
    arpScale: 'chromatic',
    arpSteps: defaultArpSteps(),
  },
  arp2: {
    label: 'ARP2',
    syncDivision: '1/16',
    arpMode: 'up',
    arpScale: 'minor',
    arp2Steps: defaultArp2Steps(),
    arpLength: 16,
    arpOctaveSpan: 2,
    arpTranspose: 0,
    arpChance: 100,
    arpRatchet: 1,
  },
  equalizer8: {
    label: 'EQ 8-Band',
    eqBands: defaultEqBands(),
  },
  phaser: {
    label: 'Phaser',
    rate: 0.6,
    depth: 800,
    feedback: 0.35,
    mix: 0.5,
    sync: false,
    syncDivision: '1/4',
  },
  fmSynth: {
    label: 'FM Synth',
    frequency: 220,
    modFrequency: 220,
    modAmount: 180,
    gain: 0.35,
    type: 'sine',
    modType: 'sine',
  },
  subOsc: {
    label: 'Sub Osc',
    frequency: 110,
    gain: 0.4,
    type: 'square',
    subOctave: 1,
  },
  noiseLayer: {
    label: 'Noise Layer',
    tone: 2800,
    Q: 0.8,
    gain: 0.18,
    type: 'lowpass',
  },
  weirdMachine: {
    label: 'Mutant Box',
    frequency: 180,
    modFrequency: 84,
    modAmount: 120,
    texture: 0.45,
    chaos: 0.5,
    tone: 1800,
    Q: 1.4,
    rate: 3.5,
    depth: 900,
    drive: 2.2,
    gain: 0.22,
    sync: false,
    syncDivision: '1/8',
    steps: [true, false, true, false, true, true, false, true],
    type: 'sawtooth',
    modType: 'square',
  },
  chaosShrine: {
    label: 'Chaos Shrine',
    frequency: 110,
    modFrequency: 72,
    modAmount: 140,
    texture: 0.55,
    chaos: 0.72,
    tone: 900,
    Q: 4.5,
    rate: 2.5,
    depth: 1100,
    drive: 2.8,
    gain: 0.24,
    detune: 18,
    blend: 0.58,
    spread: 8,
    pan: 0,
    morph: 0,
    sceneA: 'nebula',
    sceneB: 'ritual',
    sync: true,
    syncDivision: '1/16',
    freeze: false,
    steps: [true, false, true, true, false, true, false, true, true, false, false, true, false, true, true, false],
    type: 'sawtooth',
    modType: 'triangle',
  },
};
